package com.productshop.productservice.service;

import java.util.List;

import org.springframework.stereotype.Service;

import com.productshop.productservice.dto.ProductRequest;
import com.productshop.productservice.dto.ProductResponse;
import com.productshop.productservice.model.Product;
import com.productshop.productservice.repository.ProductRepository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Service
@RequiredArgsConstructor				// in place of constructor Injection of ProductRepository (we could have used @Autowired then we won't need to use this, since autowire make sure that the dependency injection happens behind the scene(abstracted from us)
@Slf4j
public class ProductService {
	
	private final ProductRepository productRepository;


//	we can use RequiredArgsConstructor  in place of this Constructor injection

//	ProductService(ProductRepository productRepository){
//		this.productRepository= productRepository;
//	}

	public void createProduct(ProductRequest productRequest) {
//		since now, we need to save the coming data into db so we need to change the dto to actual model
//		now we need to convert our ProductRequest DTO to Product POJO to save in our DB
		System.out.println("in createProduct - service");
		Product product = Product.builder()
				  .name(productRequest.getName())
				  .description(productRequest.getDescription())
				  .price(productRequest.getPrice())
				  .build();

//		Id was autogenerated so no  need to worry about it , ID will be generated while saving into DB.
		
		productRepository.save(product);		
		log.info("Product {} is saved ",product.getName());
	}
	
	public List<ProductResponse> getAllProducts(){
		List<Product> products=  productRepository.findAll();			// we will recieve result of type Product from DB
		return products.stream().map(product -> mapToProductResponse(product)).toList();					// and we need to convert Product into ProductResponse DTO to use it for further uses

//		return products.stream().map(this::mapToProductResponse).toList();				// this can be used to as a method refrence 
	}
	
	private ProductResponse mapToProductResponse(Product product) {
		return ProductResponse.builder()
				.id(product.getId())
				.name(product.getName())
				.description(product.getDescription())
				.price(product.getPrice())
				.build();
	}
}
